name: Workflows level Environment Variables 
# ref: https://www.youtube.com/watch?v=hIsvtX2G-4Q&list=PLBrle6N86WsSOfx9CuWhJTji15KTSD41m&index=11 
on:
  push:
    branches: [main]
    
env:
  CHANNEL_NAME: InterviewPro
  # put quotes in the "string" or not by default env is always string
  VIEWER_COUNT: 10000

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello, ${{ env.CHANNEL_NAME }}!"
      - name: Get comments on ${{ env.CHANNEL_NAME }}
        run: |
          #HTTPS /api/comments
          echo "Awesome!!"
          echo "Great content"
          echo "Thanks you for sharing."

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello, ${{ env.CHANNEL_NAME }}!"
