name: Job output

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    # for job output, use outputs:
    outputs:
      age: 23
      # job1 can access its own step outputs
      job1_name: "${{ steps.set-output.outputs.name }}"
      
    steps:
      - name: set output
        id: set-output
        run: |
          echo "name=InterviewPro" >> $GITHUB_OUTPUT

      - name: access output
        run: |
          echo "The value of output name is: ${{ steps.set-output.outputs.name }}"

  job2:
    runs-on: ubuntu-latest
    # create dependency so that job2 can access job1 outputs
    needs: job1 
    steps:
      - name: access output
        run: |
          echo "The value of output name is: ${{ needs.job1.outputs.job1_name }}"
          echo "The value of output name is: ${{ needs.job1.outputs.age }}"
