name: Manual Workflow

# workflow_dispatch.input allows for type of fields: string,integer,choice,boolean
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      age:
        description: 'Age'
        type: number
        required: true
      sex:
        description: Sex
        type: choice
        options:
          - Male
          - Female
          - Trans
      Married:
        description: 'is Married?'
        type: boolean

jobs:
  manual:
    runs-on: ubuntu-slim

    steps:
      - name: Greetings
        run: echo "${{ inputs.name }}"
      - name: Age
        run: echo ${{ inputs.age }}
      - name: Sex
        run: echo ${{ inputs.sex }}
      - name: Married
        run: echo ${{ inputs.married }}
