name: Scheduled Workflow

on:
  schedule:
    # scheduled every 10 minutes if */10
    - cron: '*/1 * * * *'
  # optional: Allow manual trigger also
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-slim
    steps:
      - name: Log time
        run: |
          current_date_time=$(date)
          echo "Current date and time: $current_date_time"
