name: Scheduled Workflow

on:
  workflow_dispatch:
    schedule:
      # scheduled every 10 minutes every day
      - cron: '*/10 * * * *'

jobs:
  demo:
    runs-on: ubuntu-slim
    steps:
      - name: Log time
        run: |
          current_date_time=$(date)
          echo "Current date and time: $current_date_time"
